* Амелия (05.10.2012)
** 29.04.2013
   За неделю до 7 месяцев встала в кроватке.
   пискуля - страшная!(разговоры, песни)
** 13.06.2013
   Вот-вот встанет и пойдет. Зуб пробился почти неделю назад. Долгожданный! :) 
   Очень веселит Елисея, очень. И получает от него регулярно. Постепенно привыкает. Спит уже гораздо лучше.
* Елисей (05.04.2011)
  ...очень большой пропуск...
** 05.04.2013 - 05.05.2013
   ходит на горшок, жестко реагирует, если не по-его, 
   визжит, истерит. 
   Легко раскладывает по просьбе (т.е. понимает на слух) 
   основные геометрические фигуры (круг, квадрат, треугольник, 
   прямоугольник, овал). Любит советские мультики (особенно - Чуня, Чебурашка, Винни Пух, веселая карусель).
   Любовь к шалупени, типа барбоскиных и маши с медведем, быстро затмилась вышеозвученными шедеврами.
   Порой поток слов такой, что ничего, кроме как поддакивать, не остается. Мысли пока что впереди речи :)
*** Словарный запас
да(очень тоненьким голоском - умильно, просто ложись),
н'еа(нет - проглатывая две гласные в одну и мотая головой
и/или отталкивая рукой нежеланный предмет),
дай, [т|ч]ин'и(чини, тяни), ак'уку(открой),
пипа(кнопка), гои[ки](гвозди), куи[ки](ключи),
кук'[у|о]кикики(кружочек), авав(овал)
тюктюктюк(молоток),дюдюдю[ка](дрель, шуруповерт, пылесос 
и любая другая подобная шумелка), [т|ч]'ика(отвертка)
вавака(ляля - производное от "уа-уа"),мама, папа, 
баба, дядя, тётя, 
вок(волк),пипипи, мямяка, аф, игого, 
дя'ка(зайка), йев(лев),гагага, утя, 
мика(мишка), ииба(рыба), кококо
н'ока(нога),у'ка(рука, ухо),попа,пуп,
йюби[ки](зубы),сопики(сопли),пи-пи,к'ака, аё(алё),
[c|щ]юп(суп), момоми(макароны), тит'ити(сосиска),
агу'ка(огурка=огурец),бу'ка(булка), [c|щ]апа(шапка),
[с|х]ини(синий), [с|х]ё(всё) кане(конец) (обычно вместе)
биби[би][ка](машина, причем как авто, так и стиралка..да и любая:)
коронное - айяйяй и ойёйёй, атата (уже познали, что это)
агонки (что-то горячее), 
** 05.05.2013 - 05.06.2013
ходит исключительно на горшок

а-а-а (по-большому), йобик (лобик), бадада (борода), г'оуа (голова или волосы ?), 
[с+х]ёк (сок), пи[с+х]я, кабакик (кораблик), ипух (виннипух), "йев - ааа, вок - ууу". 
Аме'ка (Амелька), [с+х]ей (Елисей), папа [с+х]ёма, мама [с+х]еня, баба йена, баба йюда.
Это сливки, а повторяет вообще почти все. И говорит говорит говорит, замечательный...
